name: Deploy Portfolio to Public Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v3

      - name: Deploy to public repo
        run: |
          git config --global user.name "Suvashish Chakraborty"
          git config --global user.email "suvashish991@gmail.com"

          git clone https://x-access-token:${{ secrets.PORTFOLIO_DEPLOY }}@github.com/Shuvo991/suvashish-portfolio-live.git public-repo

          rsync -av --exclude='.git' ./ public-repo/

          cd public-repo
          git add .
          git commit -m "Deploy portfolio" || echo "No changes to commit"
          git push
